import { BlackBoxed } from "../Boxed.tsx";
import PageBodyContent from "./PageBodyContent.tsx";

export default function PageBody() {
	return (
		<>
			<BlackBoxed>
				<PageBodyContent header={"About"} content={[]} />
			</BlackBoxed>

			<BlackBoxed>
				<PageBodyContent
					header={"Projects"}
					content={[
						{
							text: "My personal website",
							link: "takodapaschel.com",
							sourceLink: "the-site",
						},
						{
							text: "SerBytes, a data serializer",
							link: "serbytes",
							isSource: true,
						},
						{
							text: "Napoleon Amp, a music client for locally saved audio files",
							link: "napoleon_amp",
							isSource: true,
						},
						{
							text: 'SerBytes debugger, a tool used to view and debug the output of my data serializer, "Serbytes"',
							link: "serbytes_debugger",
							isSource: true,
						},
						{
							text: "Fun, purely entertainment gambling discord bot",
							link: "dig-gamba-bot",
							isSource: true,
						},
						{
							text: "Ghoulish, a Minecraft utility modification",
							link: "ghoulish",
							isSource: true,
						},
						{
							text: 'A tool to view configs generated by my Minecraft modification, "Ghoulish"',
							link: "cfg-viewer",
							isSource: true,
						},
						{
							text: "Lidar based game for a game jam",
							link: "fgj2-signal-jam",
							isSource: true,
						},
						{
							text: "Platformer based game for a game jam",
							link: "bevy-jam-5",
							isSource: true,
						},
						{
							text: "Simple Game of Life (gol) implementation for the Bevy game engine",
							link: "bevy_game_of_life",
							isSource: true,
						},
						{
							text: "A simple id library made to use less data than uuids",
							link: "simple_id",
							isSource: true,
						},
						{
							text: "A discord bot meant to monitor the uptime of a minecraft server",
							link: "servermonitor",
							isSource: true,
						},
					]}
				/>
			</BlackBoxed>
		</>
	);
}
